### PR TITLE
Logo, new searchbox and images/description at search

### PR DESCRIPTION
**Pull request by LFriede**
Hi, got three changes for you.

In the first commit i changed the search function, Movian has a searchbox so it makes the dialog unnecessary and looks nicer.

Second commit changes the logo to a more "official" one, they use it as favicon and in the android app (where i got it from), hope you like it.

Third commit adds descriptions and images to the search results. This is done with asynchronous http requests so it doesn't affect the page loading time =)
Because of this the language image had to be replaced. I added a dictionary with iso language codes and added the language in the video name, which makes it a bit longer but in my opinion it still looks nicer than the stretched language flag icons.

Liebe Grüße ;)

### CODE REVIEW

**Comment by BuXXe** [comment]
Thanks for your effort. Great changes but the logo is a bit problematic. I am not sure if we may use the logo for the plugin due to copyright / license stuff. If you could ask the kinox.to crew for permission it would be possible. I will try to include the other changes as soon as possible.

**Comment by LFriede** [comment]
I'll try to ask the crew. If i'm getting an answer i will post it here.

**Comment by LFriede** [comment]
Hi BuXXe,
i didn't receive an answer for now (and honestly i don't expect one) so i added a fourth commit which reverts the logo change.

**Comment by BuXXe** [comment]
yeah i thought so either. will merge the request and add a Release when i have some free time thx

**Comment by LFriede** [comment]
Nice =) Don't hurry with the release, wanted to look over the hosters. Maybe there will be another patch soon.

**Pull request merged**
